[package]
name = "temp-converter"
version = "0.1.0"
authors = ["rajshahuk <raj@12nines.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
